// <auto-generated />
namespace Project.Layer.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20170611scritpbd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20170611scritpbd));
        
        string IMigrationMetadata.Id
        {
            get { return "201711061739505_20170611-scritp-bd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
